apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xrediscaches.platform.vivo.infra.aws
spec:
  scope: Namespaced
  group: platform.vivo.infra.aws
  names:
    kind: XRedisCache
    plural: xrediscaches
    singular: xrediscache
    shortNames:
      - rc
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
      #o que o dev pode configurar
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    clusterId:
                      type: string
                      description: Identificador único do cluster ElastiCache.
                      pattern: "^[a-z][a-z0-9-]{0,19}$"
                      x-kubernetes-validations:
                        - rule: "self == oldSelf"
                          message: "clusterId é imutável após a criação."
                    region:
                      type: string
                      description: Região AWS onde o cluster Redis será criado.
                      default: us-east-1
                      enum:
                        - us-east-1
                    nodeType:
                      type: string
                      description: Tipo de instância do node (ex. cache.t3.micro).
                      default: cache.t3.micro
                    numCacheNodes:
                      type: integer
                      description: Número de nós no cluster.
                      default: 1
                      minimum: 1
                      maximum: 1
                    engineVersion:
                      type: string
                      description: Versão do Redis gerenciado pela AWS.
                      default: "7.1"
                    subnetIds:
                      type: array
                      description: IDs das subnets (VPC) onde o Redis será provisionado.
                      minItems: 2
                      x-kubernetes-validations:
                        - rule: "self.size() >= 2"
                          message: "Informe pelo menos duas subnets."
                      items:
                        type: string
                        pattern: "^subnet-[a-z0-9]+$"
                  required:
                    - clusterId
                    - subnetIds
              required:
                - parameters
